[build]
command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
publish = "staticfiles"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
PYTHON_VERSION = "3.11"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "functions" 